spring:
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  datasource:
    url: jdbc:postgresql://db:5432/night_club
    username: n_admin
    password: admin
    platform: postgresql
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

flyway:
    url: jdbc:postgresql://db:5432/night_club
    schemas: public
    user: n_admin
    password: admin

#  spring.flyway.baseline-on-migrate = true
#  flyway.url = jdbc:mysql://localhost:3306/mysql
#  flyway.schemas = USERSERVICE
#  flyway.user = root
#server:
#  port: 8080
#  flyway.password = root